source/GitQuery/Controllers/DbasesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Threading.Tasks;
using GitQuery.Models;
using System.Data.SqlClient;
using System.IO;
using System.Data.Common;

namespace GitQuery.Controllers
{
    public class DbasesController : Controller
    {
        private ApplicationDbContext Userdb;
        private UserManager<ApplicationUser> manager;
        private UserStore<ApplicationUser> store;
        private ApplicationDbContext db = new ApplicationDbContext();
        private string[] dbNames = {"Oracle", "MySQL", "MS SQL Server", "PostgreSQL"};

        public DbasesController()
        {
            Userdb = new ApplicationDbContext();
            store = new UserStore<ApplicationUser>(Userdb);
            manager = new UserManager<ApplicationUser>(store);
        }

        // GET: Dbases
        public async Task<ActionResult> Index()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Home");
            }
            var currentUser = await manager.FindByIdAsync(User.Identity.GetUserId());
            ViewBag.Commits = currentUser.commits;
            if (currentUser.commits.Count > 0)
            {
                ViewBag.First = currentUser.commits.First();
                ViewBag.Day = ViewBag.First.created_at.DayOfWeek;
            }
            foreach(Dbase b in currentUser.bases.ToList())
            {
                // if a new Dbase has been created, but not authenticated, remove it
                if(!b.authenticated)
                {
                    currentUser.bases.Remove(b);
                    Userdb.Bases.Remove(b);
                    Userdb.SaveChanges();
                }

                // if a user began the 'Undo Query' process but did not finish, delete the associated 'updates.txt'. It contains temporary/private info
                if (b.badCommit != -1)
                {
                    Commit com = Userdb.Commits.Find(b.badCommit);
                    System.IO.File.Delete(Server.MapPath("~/App_Data/" + com.User.Email + "/" + com.name + "/updates.txt"));
                    com.uid = "*";
                    com.password = "*";
                    b.badCommit = -1;
                    Userdb.SaveChanges();
                }

                // if a commit was created more than a month ago, remove it from GitQuery database and delete all of its data
                foreach(Commit c in b.commits)
                {
                    if(Math.Abs(DateTime.Today.DayOfYear - c.created_at.DayOfYear) > 31)
                    {
                        Directory.Delete(Server.MapPath("~/App_Data/" + c.User.Email + "/" + c.name), true);
                        Userdb.Commits.Remove(c);
                        b.commits.Remove(c);
                        Userdb.SaveChanges();
                    }
                }
            }
            return View(currentUser.bases);
        }

        // GET: Dbases/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Home");
            }
            var currentUser = await manager.FindByIdAsync(User.Identity.GetUserId());
            if (id == null)
            {
                id = currentUser.currentID;
            }
            Dbase dbase = db.Bases.Find(id);
            if (dbase == null)
            {
                return HttpNotFound();
            }
            currentUser.currentID = dbase.ID;
            Userdb.SaveChanges();

            // take the last 10 commits. of these, find out when the oldest commit was created at
            ViewBag.Commits = dbase.commits.Skip(Math.Max(0, dbase.commits.Count - 10));
            if (ViewBag.Commits.Count > 0)
            {
                ViewBag.First = dbase.commits.First();
                ViewBag.Day = ViewBag.First.created_at.DayOfWeek;
            }
            return View(dbase);
        }

        // GET: Dbases/Create
        public ActionResult Create(int? step, int? dbType)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Home");
            }
            if (step == null){ViewBag.Step = 0;}
            else 
            {
                ViewBag.Step = step;
                ViewBag.dbType = dbType;
            }
            ViewBag.Error = "";
            return View();
        }

        // POST: Dbases/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "ID,name,server,dbType")] Dbase dbase)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Home");
            }
            var currentUser = await manager.FindByIdAsync(User.Identity.GetUserId());
            ViewBag.Step = 1;
            if (ModelState.IsValid)
            {
                // For some reason, the HiddenFor for model.dbType in Create.cshtml always sets 'value' equal to an int when converted to HTML. 
                // So, this conversion is neccessary
                dbase.dbType = dbNames[Convert.ToInt32(dbase.dbType)];
                Userdb.Bases.Add(dbase);
                dbase.User = currentUser;
                await Userdb.SaveChangesAsync();
                currentUser.bases.Add(dbase);
                currentUser.currentDB = currentUser.bases.Last();
                currentUser.currentID = dbase.ID;
                await Userdb.SaveChangesAsync();
                ViewBag.Step = 2;
            }

            return View(dbase);
        }

        [ActionName("Create2")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(String username, String pass)
        {
            await Task.Delay(1000);
            var currentUser = await manager.FindByIdAsync(User.Identity.GetUserId());
            ViewBag.Step = 2;
            Dbase curDB = Userdb.Bases.Find(currentUser.currentID);
            string connectionString =
                "Data Source=" + curDB.server +
                ";Initial Catalog=" + curDB.name;
            connectionString += ";User Id=" + username +
                                ";Password=" + pass + ";";
            ViewBag.Error = "";
            using (DbConnection connection = QueryController.getConnectionType(connectionString, curDB.dbType))
            {
                // Open the connection  
                try
                {
                    connection.Open();
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.Message);
                    return RedirectToAction("Error");
                }
            }
            if(ViewBag.Error == "")
            {
                currentUser.currentDB.authenticated = true;
                Userdb.SaveChanges();
            }
             
            return RedirectToAction("Index");
        }

        // GET: Dbases/Edit/5
        public ActionResult Error()
        {
            return View();
        }

        // GET: Dbases/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Dbase dbase = db.Bases.Find(id);
            if (dbase == null)
            {
                return HttpNotFound();
            }
            return View(dbase);
        }

        // POST: Dbases/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,name,server")] Dbase dbase)
        {
            if (ModelState.IsValid)
            {
                db.Entry(dbase).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(dbase);
        }

        // GET: Dbases/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Dbase dbase = db.Bases.Find(id);
            if (dbase == null)
            {
                return HttpNotFound();
            }
            return View(dbase);
        }

        // POST: Dbases/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Dbase dbase = db.Bases.Find(id);
            db.Bases.Remove(dbase);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

source/GitQuery/Views/Dbases/Create.cshtml
@model GitQuery.Models.Dbase

<script src="@Url.Content("~/Scripts/Commits.js")" type="text/javascript"></script>

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Add a Database</h2>
<div>
    @Html.ActionLink("Back", "Index")
</div>

<div class="col-md-3">
    <h4>1: Choose a database</h4>

    <input id="Oracle" type="image" onclick='selectDB(0)' src="~/Images/Oracle.jpg">
    <input id="MySQL" type="image" onclick='selectDB(1)' src="~/Images/MySQL.png"><p></p>
    <input id="MS SQL Server"  type="image" onclick='selectDB(2)' src="~/Images/MS.png"><p></p>
    <input id="PostgreSQL" type="image" onclick='selectDB(3)' src="~/Images/PSQL.gif"><p></p>
</div>

<div class="col-md-1"></div>

    @if (ViewBag.Step == 1 || ViewBag.Step == 2)
    {
        <div class="col-md-3">
            <h4>2: Connect</h4>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <div class="col-md-offset-1">
                        <div class="text-danger">@ViewBag.Error</div>
                    </div>

                    @Html.HiddenFor(model => model.dbType, new { @value = ViewBag.dbType, @class = "form-control" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.server, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <div class="col-md-offset-2">
                                @if (ViewBag.Step == 1){ <small>*name or 'IP Address,Port'</small> }
                                @Html.EditorFor(model => model.server, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.server, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <div class="col-md-offset-2">
                                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>

                    <div id="hidden"></div>

                    @if (ViewBag.Step == 1)
                    {
                        <div class="form-group">
                            <div class="text-right">
                                <input type="button" value="Back" onclick="location.href='@Url.Action("Index", "Dbases")'" class="btn btn-default" />
                                <input type="submit" value="Connect" formaction='@Url.Action("Create")' class="btn btn-default" />
                            </div>
                        </div>
                    }
                </div>
            }
        </div>
    }
<div class="col-md-1"></div>
    @if (ViewBag.Step == 2)
    {
        <div class="col-md-3">
            <h4>3: Log In</h4>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.Label("Username", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <div class="col-md-offset-2">
                                @Html.Editor("username", new { htmlAttributes = new { @class = "form-control" } })
                            </div>
                        </div>
                    </div>

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.Label("Password", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <div class="col-md-offset-2">
                                @Html.Editor("pass", new { htmlAttributes = new { @type = "password", @class = "form-control" } })
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="text-right">
                            <input type="button" value="Back" onclick="location.href='@Url.Action("Create", "Dbases")'" class="btn btn-default" />
                            <input type="submit" value="Log In" formaction='@Url.Action("Create2")' class="btn btn-default" />
                        </div>                
                    </div>

                </div>
            }
        </div>
    }



    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

source/GitQuery/Views/Dbases/Delete.cshtml
@model GitQue.Models.Dbase

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Dbase</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.server)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.server)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

source/GitQuery/Views/Dbases/Details.cshtml
@model GitQuery.Models.Dbase

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>@Model.name</h1>
<div>
    @Html.ActionLink("Back", "Index")
</div>

<div class="col-md-5">
    <div class="text-center">
        <div class="text-center"><a class="btn btn-default btn-md" href="@Url.Action("New", "Commits")">New Query</a></div><p></p>
        @if (Model.commits.Count != 0)
        { 
            <div class="text-center"><a class="btn btn-default btn-md" href="@Url.Action("Undo", "Commits")">Undo Query</a></div>
        }
    </div>
</div>

<div class="col-md-2"></div>

<div class="col-md-5">
    <div class="well">
        <h3>Recent Queries</h3>
        <table class="table">
            @{
                if (Model.commits.Count == 0)
                {
                    <tr>*no items to display, to make a query, click 'New Query'</tr>
                }
            }

            @foreach (var com in Model.commits)
            {
                if (com.created_at.DayOfWeek != ViewBag.Day || com.ID == ViewBag.First.ID)
                {
                    <tr class="noBorder">
                        <th>
                            <div class="text-center">
                                @com.created_at.ToString("dddd, MMM d")
                            </div>
                        </th>
                    </tr>
                    ViewBag.Day = com.created_at.DayOfWeek;
                }
                <tr class="noBorder">
                    <td>
                        <div class="text-left">
                            @{String url = "/Commits/Details/" + com.ID;}
                            <a href=@url>@com.name</a>
                        </div>
                    </td>
                    <td>
                        <div class="text-center">
                            @com.created_at.ToString("t")
                        </div>
                    </td>
                </tr>
            }
        </table>
    </div>
    <p>*Click name for details</p>
</div>

source/GitQuery/Views/Dbases/Edit.cshtml
@model GitQue.Models.Dbase

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Dbase</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.server, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.server, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.server, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

source/GitQuery/Views/Dbases/Index.cshtml
@model IEnumerable<GitQuery.Models.Dbase>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Home</h1>
<p>

    <div class="well col-md-5">

        <h3>My Databases</h3>
        <table class="table">

            @foreach (var item in Model)
            {
                <tr class="noBorder">
                    <td>
                        @Html.DisplayFor(modelItem => item.name)
                    </td>
                    <td class="text-center">
                        <div class="col-md-offset-5"><a class="link-hover-color" href="/Dbases/Details/@item.ID"><u>Manage</u></a></div>
                    </td>
                </tr>
            }


        </table>
        <div class="text-right">
            <input type="button" value="Add New" onclick="location.href='@Url.Action("Create", "Dbases" )'" class="btn btn-default" />
        </div>

    </div>
    <div class="col-md-2"></div>

    <div class="col-md-5">
        <div class="well">
            <h3>Recent Queries</h3>
            <table class="table">
                @{
                    if (ViewBag.Commits.Count == 0)
                    {
                        <tr>*no items to display, to make a new query select a database to manage.</tr>
                    }
                }

                @foreach (var com in ViewBag.Commits)
                {
                    if (com.created_at.DayOfWeek != ViewBag.Day || com.ID == ViewBag.First.ID)
                    {
                        <tr class="noBorder">
                            <th>
                                <div class="text-center">
                                    @com.created_at.ToString("dddd, MMM d")
                                </div>
                            </th>
                        </tr>
                        ViewBag.Day = com.created_at.DayOfWeek;
                    }
                    <tr class="noBorder">
                        <td>
                            <div class="text-left">
                                @{String url = "/Commits/Details/" + com.ID;}
                                <a href=@url><u>@com.name</u></a>
                            </div>
                        </td>
                        <td>
                            <div class="text-right">
                                @com.created_at.ToString("t")
                            </div>
                        </td>
                    </tr>
                }
            </table>
        </div>
<p>*Click name for details</p>
    </div>