source/GitQuery/Models/Commit.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Linq;
using System.Web;

namespace GitQuery.Models
{
    public class Commit
    {
        public int ID { get; set; }

        [Required]
        [Display(Name = "Query Name")]
        public string name { get; set; }
        public virtual ApplicationUser User { get; set; }
        public virtual Dbase db { get; set; }

        [Display(Name = "Created At")]
        [DisplayFormat(DataFormatString = "{0:g}", ApplyFormatInEditMode = true)]
        public DateTime created_at { get; set; }

        [Required]
        [Display(Name = "Username")]
        public String uid { get; set; }
        
        [Required]
        [Display(Name = "Password")]
        public String password { get; set; }

        [Display(Name = "Table")]
        public String table { get; set; }

        [Display(Name = "Records Affected")]
        public int numRows { get; set; }

        [Required]
        [Display(Name = "SQL")]
        public String sqlQuery { get; set; }
        public String key { get; set; }
    }
}

source/GitQuery/Controllers/CommitsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GitQuery.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Threading.Tasks;
using System.Data.SqlClient;
using System.IO;
using Newtonsoft.Json;
using System.Xml.Serialization;
using Newtonsoft.Json.Linq;
using System.Security.Cryptography;
using System.Text;
using System.IO.Compression;
using Oracle.ManagedDataAccess.Client;
using System.Data.Common;

namespace GitQuery.Controllers
{
    public class CommitsController : Controller
    {

        private ApplicationDbContext Userdb;
        private UserManager<ApplicationUser> manager;

        // Constants used for custom errors in the New and Undo actions
        public const String SyntaxError = "Error: Please check the syntax of your query statement.";
        public const String QueryTypeError = "Error: We're sorry, at this time we only support SQL UPDATE statements.";
        public const String LoginError = "Error: There was a problem processing this query. Please make sure you have entered the correct information, have permission to update this database, and have enabled the server to accecpt remote connections.";
        public const String illegalSQL = "SELECT INSERT DELETE CREATE DROP ALTER";

        private ApplicationDbContext db = new ApplicationDbContext();

        public CommitsController()
        {
            Userdb = new ApplicationDbContext();
            manager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(Userdb));
        }

        //GET
        public async Task<ActionResult> Undo()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Home");
            }
            var currentUser = await manager.FindByIdAsync(User.Identity.GetUserId());
            ViewBag.Success = false;
            ViewBag.Method = "get";
            return View(currentUser.commits);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        /* POST
        | Reconcile data, then create an 'updates.txt' file that contains the SQL UPDATE statements that will undo the changes of the
        | selected query */
        public async Task<ActionResult> Undo(int id, String username, String pass)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Home");
            }
            var currentUser = await manager.FindByIdAsync(User.Identity.GetUserId());
            Commit commit = db.Commits.Find(id);
            commit.uid = username;
            commit.password = pass;
            List<String> updates = reconcile(commit);   // returns list of SQL UPDATE statements

            // Create 'updates.txt' file, where each line is a String from the above List
            String datafile = Server.MapPath("~/App_Data/" + commit.User.Email + "/" + commit.name + "/updates.txt");
            FileStream fs = new FileStream(datafile, FileMode.Create);
            StreamWriter sw = new StreamWriter(fs);
            foreach(String s in updates)
            {
                sw.WriteLine(s);
            }
            sw.Close();

            ViewBag.numChanged = countChanged(updates);
            ViewBag.Commit = commit;
            ViewBag.Method = "post";
            commit.db.badCommit = commit.ID;
            db.Entry(commit).State = EntityState.Modified;
            await db.SaveChangesAsync();
            return View(currentUser.commits);

        }

        public async Task<ActionResult> Index()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Home");
            }
            var currentUser = await manager.FindByIdAsync(User.Identity.GetUserId());
            return View(currentUser.commits);
        }

        // GET: Commits
        public ActionResult New()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Home");
            }
            ViewBag.Method = "get";
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        // GET
        // Parse query and check for errors, connect to database and count the number of rows that will be affected by the query
        public async Task<ActionResult> New([Bind(Include = "ID,name,sqlQuery,uid,password")] Commit commit)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Home");
            }
            var currentUser = await manager.FindByIdAsync(User.Identity.GetUserId());
            if (ModelState.IsValid)
            {
                ViewBag.Method = "post";
                // If there is an error, set ViewBag.Error equal to message
                string[] words = commit.sqlQuery.Split(' ');
                if (illegalSQL.Contains(words[0])) { ViewBag.Error = true; ViewBag.Message = QueryTypeError; }
                else if (words.Length < 4) { ViewBag.Error = true; ViewBag.Message = SyntaxError; }

                // Else, count the number of rows that will be changed by the query
                else
                {
                    Dbase curDB = Userdb.Bases.Find(currentUser.currentID);
                    ViewBag.Message = countRowsAffected(commit, curDB);
                    if (ViewBag.Message[0] == 'E') { ViewBag.Error = true; }
                    else { ViewBag.Error = false; }
                    ViewBag.Table = getTableName(commit.sqlQuery);
                    ViewBag.DB = curDB.name;
                }
            }
            ViewBag.key = commit.key;  // First field in the db table that is a table key. Used as the unique identifier for each afftected row
            return View(commit);
        }

        // GET: Commits/Details/5
        public ActionResult Details(int? id)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Home");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Commit commit = db.Commits.Find(id);
            if (commit == null)
            {
                return HttpNotFound();
            }
            return View(commit);
        }

        // POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Details(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Commit commit = db.Commits.Find(id);
            if (commit == null)
            {
                return HttpNotFound();
            }
            return View(commit);
        }

        // GET: Commits/Create
        public ActionResult Create()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        // POST: Commits/Create
        // Store the old data affected by the query, execute the query, store the new data from the fields affected by query
        // 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "ID,name,sqlQuery,uid,password,key")] Commit commit)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Home");
            }
            var currentUser = await manager.FindByIdAsync(User.Identity.GetUserId());
            DataTable table;
            if (ModelState.IsValid)
            {
                commit.User = currentUser;
                table = resultSetTable(commit); // datatable filled with old data affected by query
                String path = "~/App_Data/" + commit.User.Email + "/" + commit.name + "/" + commit.name + ".txt";
                createFile(table, commit, path); // serialize the table to folder ~/App_Data/commit.User.Email/commit.name

                // save these fields of commit and add to database
                commit.table = getTableName(commit.sqlQuery);
                commit.numRows = table.Rows.Count;
                commit.created_at = DateTime.Now;
                commit.db = Userdb.Bases.Find(currentUser.currentID);
                Userdb.Commits.Add(commit);
                currentUser.commits.Add(commit);

                executeQuery(commit);
                List<int> ids = getUniques(table);  // get unique identifiers for the rows affected by the query
                storeNewData(table, commit, ids);    // store the new data from the rows affected by query
                commit.uid = "*";
                commit.password = "*";
                await Userdb.SaveChangesAsync();
                return View();
            }
            return RedirectToAction("New");
        }

        // GET: Commits/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Commit commit = db.Commits.Find(id);
            if (commit == null)
            {
                return HttpNotFound();
            }
            return View(commit);
        }

        // POST: Commits/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.

source/GitQuery/Views/Commits/Create.cshtml
<script src="@Url.Content("~/Scripts/Commits.js")" type="text/javascript"></script>
<script>
    confirmQuery(@ViewBag.RowsAffected);
</script>

source/GitQuery/Views/Commits/Details.cshtml
@model GitQuery.Models.Commit

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Message</h2>

<div>
    <h4>@Html.ValueFor(model => model.name)</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.created_at)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.created_at)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.db.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.db.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.db.server)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.db.server)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.table)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.table)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.sqlQuery)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sqlQuery)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.numRows)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.numRows)
        </dd>
    </dl>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
    <input type="button" value="Undo this query" onclick="location.href='@Url.Action("Undo", "Commits", Model.ID)'" class="btn btn-default" />
    }
</div>

source/GitQuery/Views/Commits/Edit.cshtml
@model GitQue.Models.Commit

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Commit</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.created_at, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.created_at, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.created_at, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.database, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.database, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.database, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.server, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.server, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.server, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.uid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.uid, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.uid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.table, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.table, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.table, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.numRows, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.numRows, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.numRows, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.sqlQuery, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.sqlQuery, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.sqlQuery, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.filepath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.filepath, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.filepath, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

source/GitQuery/Views/Commits/New.cshtml
@model GitQuery.Models.Commit
@{
    ViewBag.Title = "New";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Run New Query</h2>
<div>
    @Html.ActionLink("Back", "Details", "Dbases")
</div>


@using (Html.BeginForm())
{
    <div class="col-md-6">

        @Html.AntiForgeryToken()
        <div class="form-horizontal">
            <hr />
            <div class="col-md-offset-1">
                <div id="error" class="text-danger"></div>
            </div>

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <h3>Query</h3>

            <div class="col-md-offset-2">
                <div class="form-group">
                    @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-7">
                        @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class=" form-group">
                    @Html.LabelFor(model => model.sqlQuery, htmlAttributes: new { @class = "control-label col-md-2" })
                            @Html.TextAreaFor(model => model.sqlQuery, new { @style = "width: 450px; height: 75px", @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.sqlQuery, "", new { @class = "text-danger" })
                    </div>
            </div>

            <h3>Log In</h3>

            <div class="col-md-offset-2">
                <div class="form-group">
                    @Html.LabelFor(model => model.uid, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-7">
                        @Html.EditorFor(model => model.uid, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.uid, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class=" form-group">

                    @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-7">
                        @Html.TextBoxFor(model => model.password, new { @type = "password", @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-4 col-md-10">
                    <input type="submit" value="Cancel" formaction='@Url.Action("Index", "Dbases")' class="btn btn-default" />
                    <input type="submit" value="Run" formaction='@Url.Action("New")' class="btn btn-default" />
                </div>
            </div>
        </div>
    </div>

    if (ViewBag.Method == "post")
    {
        @Html.HiddenFor(model => model.key, new { @value = ViewBag.key, @class = "form-control" })
    
        if (!ViewBag.Error)
        {

            <div class="col-md-6">
                <div class="text-danger"><h4><b>WARNING, please read carefully</b></h4></div>

                <div class="col-md-offset-1">
                    You are about to update <b><u>@ViewBag.Message</u></b> entries of the @ViewBag.Table table in the @ViewBag.DB database.
                    If this is the change you wish to make, click Confirm. Otherwise, you may edit your query to the left or cancel the update.
                </div>
                <p></p>
                <div class="form-group">
                    <div class="text-center">
                        <input type="submit" value="Cancel" formaction="@Url.Action("GotoIndex")" class=" btn btn-default" />
                        <input type="submit" value="Confirm" formaction="@Url.Action("Create")" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }

        else
        {
            <script>
                    document.getElementById("error").innerHTML = '@ViewBag.Message';
            </script>
        }

    }
}

source/GitQuery/Views/Commits/Undo.cshtml
@model IEnumerable<GitQuery.Models.Commit>

@{
    ViewBag.Title = "Undo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="~/Scripts/Bases.js"></script>

<h2>Select a query to undo</h2>
<p>
    @Html.ActionLink("Back", "Index", "Dbases")
</p>

@using (Html.BeginForm())
{
    <div class="col-md-5">
        @Html.AntiForgeryToken()
        <div class="form-horizontal">
            <div class="col-md-offset-1">
                <div id="error" class="text-danger"></div>
            </div>
            <div class="col-md-offset-2">
                <table class="table">
                    <tr>
                        <th>
                            Select
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.name)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.created_at)
                        </th>
                    </tr>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.RadioButton("ID", item.ID, new { onClick = "analyze(" + item.ID + ")" })
                            </td>
                            <td>
                                @{String url = "/Commits/Details/" + item.ID;}
                                <a href=@url>@item.name</a>
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.created_at)
                            </td>
                        </tr>
                    }

                </table>
                <p>*Click name for details</p>
            </div>
        </div>
    </div>
}
<div class="col-md-2"></div>

@using (Html.BeginForm())
{
    <div class="col-md-5">
        @Html.AntiForgeryToken()
        <h3 id="LoginMessage"></h3>
        <div class="form-horizontal">
            <div class="col-md-offset-1">
                <div id="commit"></div>
                <div id="user" class="form-group"></div>
                <div id="pass" class="form-group"></div>
                <div class="text-right">
                    <div id="submitLogin"></div>
                </div>
            </div>
            </div>
    </div>
}

        @if (ViewBag.Method == "post")
        {
            using (Html.BeginForm())
            {
                <div class="col-md-5">
                    @Html.AntiForgeryToken()
                    <div class="form-horizontal">
                        <div class="text-danger"><h4><b>WARNING, please read carefully</b></h4></div>
                        @if (ViewBag.numChanged == 0)
                        {
                            <div class="col-md-offset-1">
                                You are about to update <b><u>@ViewBag.Commit.numRows</u></b> records of the @ViewBag.Commit.table table in the @ViewBag.Commit.db.name database.
                                If this is the change you wish to make, click Confirm.
                            </div>

                            <div class="form-group">
                                <div class="text-center">
                                    <input type="submit" value="Cancel" formaction="@Url.Action("GotoIndex")" class=" btn btn-default" />
                                    <input type="submit" value="Confirm" formaction="@Url.Action("Delete", "Commits", new { id = ViewBag.Commit.ID, unchanged = false })" class="btn btn-default" />
                                </div>
                            </div>
                        }

                        else
                        {
                            <div class="col-md-offset-1">
                                We noticed that <b><u>@ViewBag.numChanged out of @ViewBag.Commit.numRows</u></b> of the records you wish to update have changed since this query was run. You may either:
                                <p></p>
                                <ul>
                                    <li><b>Cancel</b></li>
                                    <li><b>Undo All</b>: update all @ViewBag.Commit.numRows records</li>
                                    <li><b>Reconcile</b>: update all @ViewBag.Commit.numRows records except the @ViewBag.numChanged that have changed</li>
                                </ul>
                            </div>

                            <div class="form-group">
                                <div class="text-center">
                                    <input type="submit" value="Cancel" formaction="@Url.Action("GotoIndex")" class=" btn btn-default" />
                                    <input type="submit" value="Undo All" formaction="@Url.Action("Delete", "Commits", new { id = ViewBag.Commit.ID, unchanged = false})" class="btn btn-default" />
                                    <input type="submit" value="Reconcile" formaction="@Url.Action("Delete", "Commits", new {id = ViewBag.Commit.ID, unchanged = true})" class="btn btn-default" />
                                </div>
                            </div>
                        }
                    </div>
                </div>
            }
        }

